const PDFDocument = require('pdfkit');

const generateDocumentChecklist = (scheme, documents, user) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50 });
    const chunks = [];

    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Header
    doc.fontSize(22).fillColor('#1a6b3c').text('GramSaathi', { align: 'center' });
    doc.fontSize(14).fillColor('#333').text('Document Checklist', { align: 'center' });
    doc.moveDown();
    doc.strokeColor('#1a6b3c').lineWidth(2).moveTo(50, doc.y).lineTo(550, doc.y).stroke();
    doc.moveDown();

    // Scheme Details
    doc.fontSize(16).fillColor('#1a6b3c').text('Scheme Details');
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#333');
    doc.text(`Scheme Name: ${scheme.schemeName || scheme.name}`);
    doc.text(`Category: ${scheme.category}`);
    if (scheme.applicationDeadline) doc.text(`Deadline: ${scheme.applicationDeadline}`);
    if (scheme.ministry) doc.text(`Ministry: ${scheme.ministry}`);
    doc.moveDown();

    // User Details
    if (user) {
      doc.fontSize(16).fillColor('#1a6b3c').text('Applicant Details');
      doc.moveDown(0.5);
      doc.fontSize(11).fillColor('#333');
      doc.text(`Name: ${user.name}`);
      doc.text(`State: ${user.state} | District: ${user.district}`);
      doc.text(`Generated On: ${new Date().toLocaleDateString('en-IN')}`);
      doc.moveDown();
    }

    // Documents
    doc.fontSize(16).fillColor('#1a6b3c').text('Required Documents');
    doc.moveDown(0.5);
    doc.fontSize(11).fillColor('#333');
    documents.forEach((docItem, index) => {
      doc.rect(50, doc.y, 15, 15).stroke();
      doc.text(`  ${index + 1}. ${docItem}`, 70, doc.y - 15);
      doc.moveDown(0.8);
    });

    doc.moveDown();
    doc.fontSize(10).fillColor('#888')
      .text('Generated by GramSaathi - Connecting Rural Citizens with Opportunities', { align: 'center' });

    doc.end();
  });
};

module.exports = { generateDocumentChecklist };