require('dotenv').config({ path: require('path').resolve(__dirname, '../../.env') });
const mongoose = require('mongoose');
const Scholarship = require('../models/Scholarship');
const AgricultureScheme = require('../models/AgricultureScheme');
const ServiceCenter = require('../models/ServiceCenter');
const connectDB = require('../config/db');

const scholarships = [
  {
    name: 'Post Matric Scholarship for SC Students',
    amount: 15000,
    description: 'Scholarship for Scheduled Caste students pursuing post-matric education',
    eligibility: {
      maxFamilyIncome: 250000,
      category: ['SC'],
      gender: 'All',
      state: [],
      degree: ['Intermediate', 'Bachelor', 'Master', 'Diploma'],
      minPercentage: 50,
    },
    deadline: 'October 31',
    documents: ['Aadhaar Card', 'Caste Certificate', 'Income Certificate', 'Mark Sheet', 'Bank Passbook'],
    applicationLink: 'https://scholarships.gov.in',
    category: 'Post-Matric',
    ministry: 'Ministry of Social Justice and Empowerment',
  },
  {
    name: 'Post Matric Scholarship for ST Students',
    amount: 15000,
    description: 'Scholarship for Scheduled Tribe students pursuing post-matric education',
    eligibility: {
      maxFamilyIncome: 250000,
      category: ['ST'],
      gender: 'All',
      state: [],
      degree: ['Intermediate', 'Bachelor', 'Master', 'Diploma'],
      minPercentage: 50,
    },
    deadline: 'October 31',
    documents: ['Aadhaar Card', 'Caste Certificate', 'Income Certificate', 'Mark Sheet', 'Bank Passbook'],
    applicationLink: 'https://scholarships.gov.in',
    category: 'Post-Matric',
    ministry: 'Ministry of Tribal Affairs',
  },
  {
    name: 'Post Matric Scholarship for OBC Students',
    amount: 10000,
    description: 'Scholarship for Other Backward Classes students in post-matric courses',
    eligibility: {
      maxFamilyIncome: 150000,
      category: ['OBC'],
      gender: 'All',
      state: [],
      degree: ['Intermediate', 'Bachelor', 'Master', 'Diploma'],
      minPercentage: 50,
    },
    deadline: 'November 30',
    documents: ['Aadhaar Card', 'OBC Certificate', 'Income Certificate', 'Mark Sheet', 'Bank Passbook'],
    applicationLink: 'https://scholarships.gov.in',
    category: 'Post-Matric',
    ministry: 'Ministry of Social Justice and Empowerment',
  },
  {
    name: 'Central Sector Scholarship for College Students',
    amount: 12000,
    description: 'Merit-based scholarship for students in regular degree courses',
    eligibility: {
      maxFamilyIncome: 450000,
      category: ['General', 'OBC', 'SC', 'ST'],
      gender: 'All',
      state: [],
      degree: ['Bachelor', 'Master'],
      minPercentage: 80,
    },
    deadline: 'October 31',
    documents: ['Aadhaar Card', 'Mark Sheet', 'Income Certificate', 'Bank Passbook', 'Admission Letter'],
    applicationLink: 'https://scholarships.gov.in',
    category: 'Merit',
    ministry: 'Ministry of Education',
  },
  {
    name: 'INSPIRE Scholarship for Higher Education',
    amount: 80000,
    description: 'For students pursuing Bachelor and Master degree in Natural and Basic Sciences',
    eligibility: {
      maxFamilyIncome: 999999999,
      category: ['General', 'OBC', 'SC', 'ST'],
      gender: 'All',
      state: [],
      stream: ['Science'],
      degree: ['Bachelor', 'Master'],
      minPercentage: 85,
    },
    deadline: 'November 30',
    documents: ['Aadhaar Card', 'Mark Sheet', 'Admission Letter', 'Bank Passbook'],
    applicationLink: 'https://online-inspire.gov.in',
    category: 'Merit',
    ministry: 'Department of Science and Technology',
  },
  {
    name: 'National Means-cum-Merit Scholarship',
    amount: 12000,
    description: 'For meritorious students of economically weaker sections to arrest drop-outs at Class VIII',
    eligibility: {
      maxFamilyIncome: 150000,
      category: ['General', 'OBC', 'SC', 'ST'],
      gender: 'All',
      state: [],
      degree: ['Class IX', 'Class X', 'Class XI', 'Class XII'],
      minPercentage: 55,
    },
    deadline: 'November 15',
    documents: ['Aadhaar Card', 'Income Certificate', 'Mark Sheet', 'Bank Passbook'],
    applicationLink: 'https://scholarships.gov.in',
    category: 'Means-cum-Merit',
    ministry: 'Ministry of Education',
  },
  {
    name: 'Begum Hazrat Mahal National Scholarship for Minorities',
    amount: 10000,
    description: 'Scholarship for meritorious girls belonging to minority communities',
    eligibility: {
      maxFamilyIncome: 200000,
      category: ['General', 'OBC'],
      gender: 'Female',
      state: [],
      degree: ['Class IX', 'Class X', 'Class XI', 'Class XII'],
      minPercentage: 50,
    },
    deadline: 'September 30',
    documents: ['Aadhaar Card', 'Minority Community Certificate', 'Income Certificate', 'Mark Sheet', 'Bank Passbook'],
    applicationLink: 'https://scholarships.gov.in',
    category: 'Means-cum-Merit',
    ministry: 'Maulana Azad Education Foundation',
  },
  {
    name: 'Dr. Ambedkar Post-Matric Scholarship for EBC Students',
    amount: 8000,
    description: 'For Economically Backward Class students in post-matric studies',
    eligibility: {
      maxFamilyIncome: 100000,
      category: ['General'],
      gender: 'All',
      state: [],
      degree: ['Intermediate', 'Bachelor', 'Master', 'Diploma'],
      minPercentage: 45,
    },
    deadline: 'October 31',
    documents: ['Aadhaar Card', 'Income Certificate', 'Mark Sheet', 'Bank Passbook', 'EBC Certificate'],
    applicationLink: 'https://scholarships.gov.in',
    category: 'Post-Matric',
    ministry: 'Ministry of Social Justice and Empowerment',
  },
];

const agricultureSchemes = [
  {
    name: 'Kisan Credit Card (KCC)',
    type: 'Loan',
    description: 'Provides farmers with affordable credit for crop cultivation, post-harvest, maintenance and allied activities',
    benefits: 'Flexible revolving credit limit up to ₹3 lakh at 4% interest per annum',
    eligibility: {
      cropTypes: [],
      minLandSize: 0,
      maxLandSize: 99999,
      maxIncome: 99999999,
      state: [],
      farmingCategory: ['All Farmers', 'Tenant Farmers', 'Sharecroppers'],
    },
    documentsRequired: ['Aadhaar Card', 'Land Ownership Proof', 'Bank Passbook', 'Passport Photos'],
    applicationLink: 'https://www.nabard.org',
    applicationProcess: 'Apply at nearest bank branch with land documents',
    deadline: 'Ongoing',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
  },
  {
    name: 'PM Fasal Bima Yojana (PMFBY)',
    type: 'Insurance',
    description: 'Crop insurance scheme to protect farmers from financial losses due to crop failure',
    benefits: 'Insurance coverage for crop losses due to natural calamities, pests and diseases',
    eligibility: {
      cropTypes: ['Paddy', 'Wheat', 'Cotton', 'Maize', 'Soybean', 'Groundnut', 'Sugarcane'],
      minLandSize: 0,
      maxLandSize: 99999,
      maxIncome: 99999999,
      state: [],
      farmingCategory: ['All Farmers'],
    },
    documentsRequired: ['Aadhaar Card', 'Land Ownership Proof', 'Bank Passbook', 'Sowing Certificate'],
    applicationLink: 'https://pmfby.gov.in',
    applicationProcess: 'Apply through Common Service Centers, banks, or online portal',
    deadline: 'Seasonal - before crop sowing',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
  },
  {
    name: 'Pradhan Mantri Krishi Sinchai Yojana (PMKSY)',
    type: 'Subsidy',
    description: 'Improving water use efficiency and expanding irrigation coverage',
    benefits: 'Up to 55% subsidy for drip/sprinkler irrigation systems for small farmers',
    eligibility: {
      cropTypes: [],
      minLandSize: 0,
      maxLandSize: 99999,
      maxIncome: 300000,
      state: [],
      farmingCategory: ['Small Farmers', 'Marginal Farmers'],
    },
    documentsRequired: ['Aadhaar Card', 'Land Ownership Proof', 'Bank Passbook', 'Irrigation System Quote'],
    applicationLink: 'https://pmksy.gov.in',
    applicationProcess: 'Apply at District Agriculture Office',
    deadline: 'Ongoing',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
  },
  {
    name: 'Soil Health Card Scheme',
    type: 'Other',
    description: 'Provides soil health card to farmers with crop-wise recommendations for nutrients and fertilizers',
    benefits: 'Free soil testing and personalized fertilizer recommendations to reduce input costs',
    eligibility: {
      cropTypes: [],
      minLandSize: 0,
      maxLandSize: 99999,
      maxIncome: 99999999,
      state: [],
      farmingCategory: ['All Farmers'],
    },
    documentsRequired: ['Aadhaar Card', 'Land Ownership Proof'],
    applicationLink: 'https://soilhealth.dac.gov.in',
    applicationProcess: 'Contact nearest Agriculture Extension Officer',
    deadline: 'Ongoing',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
  },
  {
    name: 'National Agriculture Market (eNAM)',
    type: 'Other',
    description: 'Online trading platform for agricultural commodities to get better prices',
    benefits: 'Access to pan-India market, better price discovery, reduced transaction costs',
    eligibility: {
      cropTypes: [],
      minLandSize: 0,
      maxLandSize: 99999,
      maxIncome: 99999999,
      state: [],
      farmingCategory: ['All Farmers'],
    },
    documentsRequired: ['Aadhaar Card', 'Bank Passbook', 'Mobile Number'],
    applicationLink: 'https://enam.gov.in',
    applicationProcess: 'Register at nearest APMC/Mandi or online',
    deadline: 'Ongoing',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
  },
  {
    name: 'Sub-Mission on Agricultural Mechanization (SMAM)',
    type: 'Equipment',
    description: 'Financial assistance to farmers for purchase of agricultural machinery',
    benefits: '25-50% subsidy on agricultural machinery and equipment for small/marginal farmers',
    eligibility: {
      cropTypes: [],
      minLandSize: 0,
      maxLandSize: 5,
      maxIncome: 200000,
      state: [],
      farmingCategory: ['Small Farmers', 'Marginal Farmers', 'SC/ST Farmers'],
    },
    documentsRequired: ['Aadhaar Card', 'Land Ownership Proof', 'Caste Certificate (if SC/ST)', 'Bank Passbook', 'Machine Quotation'],
    applicationLink: 'https://agrimachinery.nic.in',
    applicationProcess: 'Apply at District Agriculture Office with machinery quotation',
    deadline: 'Ongoing',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
  },
  {
    name: 'PM Kisan Drone Yojana',
    type: 'Equipment',
    description: 'Financial assistance for drone purchase for precision agriculture',
    benefits: '40% subsidy (up to ₹4 lakh) for FPOs; 50% for SC/ST/Small/Marginal/Women farmers',
    eligibility: {
      cropTypes: [],
      minLandSize: 0,
      maxLandSize: 99999,
      maxIncome: 99999999,
      state: [],
      farmingCategory: ['FPO', 'SC/ST Farmers', 'Small Farmers', 'Women Farmers'],
    },
    documentsRequired: ['Aadhaar Card', 'Land Ownership Proof', 'Bank Passbook', 'FPO Registration (if applicable)'],
    applicationLink: 'https://agricoop.nic.in',
    applicationProcess: 'Apply through Agriculture Department portal',
    deadline: 'Ongoing',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
  },
  {
    name: 'Rashtriya Krishi Vikas Yojana (RKVY)',
    type: 'Subsidy',
    description: 'Holistic development of agriculture and allied sectors',
    benefits: 'Grants for infrastructure development, training, and production enhancement',
    eligibility: {
      cropTypes: [],
      minLandSize: 0,
      maxLandSize: 99999,
      maxIncome: 99999999,
      state: [],
      farmingCategory: ['All Farmers', 'FPO'],
    },
    documentsRequired: ['Aadhaar Card', 'Land Ownership Proof', 'Project Proposal', 'Bank Passbook'],
    applicationLink: 'https://rkvy.nic.in',
    applicationProcess: 'Apply through State Agriculture Department',
    deadline: 'Annual - check state notifications',
    ministry: 'Ministry of Agriculture & Farmers Welfare',
  },
];

const serviceCenters = [
  {
    name: 'MeeSeva Center - Hyderabad Banjara Hills',
    type: 'MeeSeva',
    address: 'Road No. 12, Banjara Hills, Hyderabad',
    district: 'Hyderabad',
    state: 'Telangana',
    pincode: '500034',
    location: { type: 'Point', coordinates: [78.4483, 17.4126] },
    contactNumber: '040-23456789',
    openingHours: 'Mon-Sat 9:00 AM - 6:00 PM',
    services: ['Aadhaar Update', 'Income Certificate', 'Caste Certificate', 'Birth Certificate', 'Revenue Records'],
    rating: 4.2,
  },
  {
    name: 'District Agriculture Office - Krishna',
    type: 'Agriculture Office',
    address: 'Collectorate Campus, Machilipatnam, Krishna District',
    district: 'Krishna',
    state: 'Andhra Pradesh',
    pincode: '521001',
    location: { type: 'Point', coordinates: [81.1304, 16.1875] },
    contactNumber: '08672-222345',
    openingHours: 'Mon-Fri 9:00 AM - 5:00 PM',
    services: ['PM Kisan Registration', 'Fasal Bima', 'Soil Health Card', 'KCC Applications', 'Subsidy Applications'],
    rating: 4.0,
  },
  {
    name: 'State Bank of India - Vijayawada Main Branch',
    type: 'Bank',
    address: 'Governorpet, Vijayawada, Andhra Pradesh',
    district: 'Krishna',
    state: 'Andhra Pradesh',
    pincode: '520002',
    location: { type: 'Point', coordinates: [80.6480, 16.5193] },
    contactNumber: '0866-2571234',
    openingHours: 'Mon-Fri 10:00 AM - 4:00 PM, Sat 10:00 AM - 1:00 PM',
    services: ['KCC Loans', 'Mudra Loans', 'Jan Dhan Accounts', 'Aadhaar Seeding', 'PM Kisan DBT'],
    rating: 3.8,
  },
  {
    name: 'Government General Hospital - Vijayawada',
    type: 'Hospital',
    address: 'Siddhartha Nagar, Vijayawada',
    district: 'Krishna',
    state: 'Andhra Pradesh',
    pincode: '520008',
    location: { type: 'Point', coordinates: [80.6300, 16.5100] },
    contactNumber: '0866-2475001',
    openingHours: '24/7',
    services: ['Ayushman Bharat', 'Free OPD', 'Emergency', 'Maternity Services', 'Child Health'],
    rating: 3.5,
  },
  {
    name: 'MeeSeva Center - Warangal',
    type: 'MeeSeva',
    address: 'Hanamkonda, Warangal Urban',
    district: 'Warangal',
    state: 'Telangana',
    pincode: '506001',
    location: { type: 'Point', coordinates: [79.5941, 17.9785] },
    contactNumber: '0870-2578100',
    openingHours: 'Mon-Sat 9:00 AM - 6:00 PM',
    services: ['Income Certificate', 'Residence Certificate', 'Caste Certificate', 'Land Records', 'Pension Applications'],
    rating: 4.1,
  },
  {
    name: 'District Agriculture Office - Warangal',
    type: 'Agriculture Office',
    address: 'Collector Office Campus, Warangal',
    district: 'Warangal',
    state: 'Telangana',
    pincode: '506001',
    location: { type: 'Point', coordinates: [79.5880, 17.9680] },
    contactNumber: '0870-2578200',
    openingHours: 'Mon-Fri 9:00 AM - 5:00 PM',
    services: ['PM Kisan', 'Rythu Bandhu', 'Crop Insurance', 'Seed Subsidy', 'Fertilizer Assistance'],
    rating: 4.3,
  },
];

const seed = async () => {
  await connectDB();
  try {
    await Scholarship.deleteMany({});
    await AgricultureScheme.deleteMany({});
    await ServiceCenter.deleteMany({});

    await Scholarship.insertMany(scholarships);
    await AgricultureScheme.insertMany(agricultureSchemes);
    await ServiceCenter.insertMany(serviceCenters);

    console.log(`✅ Seeded ${scholarships.length} scholarships`);
    console.log(`✅ Seeded ${agricultureSchemes.length} agriculture schemes`);
    console.log(`✅ Seeded ${serviceCenters.length} service centers`);
    process.exit(0);
  } catch (error) {
    console.error('❌ Seeding failed:', error.message);
    process.exit(1);
  }
};

seed();